serverless/serverless-azure-functions

README.md
fixes #18 
- Fixed instuctions
- Changed install command
- Expanded/corrected credentials section
- Added (optional) part to remove
- Added Contributing section
- Added LICENSE section
=> Fix instructions, add license and contributing

README.md, provider/azureProvider.js
=> Fix env casing

README.md, deploy/lib/createFunctions.js, package.json, provider/azureProvider.js, shared/utils.js
Fixes #21 
Fixes install command
Fixes readme file
Fixes http out default
=> 0.1.1 release

deploy/lib/createFunction.js, deploy/lib/createFunctions.js, package.json, provider/azureProvider.js
Use zip-folder package instead of jszip
=> Simplify zip and upload function code

shared/utils.js
=> fix a bug preventing x-azure-settings settings to have false as a value

package.json, provider/azureProvider.js
=> Support service wide environment variables

provider/azureProvider.js
Normalizes tab sizes and adds missing tabs before some return statements.
Adds the serverless package name and version to each SDK client to enable
tracking of usage.
=> Add telemetry

package-lock.json, package.json
Updated to the latest az-login to correct an issue with MSA auth and
updated to the latest version of request.
Closes #74
=> Update az-login and request dependencies.

package-lock.json, package.json, provider/azureProvider.js
This PR resolves #77 by simply displaying the device URL and code in the user's terminal when performing an interactive login. While doing this, I also removed some unused NPM dependencies and added an NPM 5+ lockfile.
=> Updating az-login logic

jest.config.js, jest.config.json, package-lock.json, package.json, src/plugins/apim/apimServicePlugin.test.ts
- Changed jest config to `js` from `json` (VS code looks for js file)
- Added `serverless` as dev dependency
- Added unit test to validate configuration
=> feat: Enabled Jest configuration to work in VS code

src/plugins/invoke/azureInvoke.ts, src/services/invokeService.ts
No work item. Pairing with Neeraj on updates to invoke plugin and service. PR into dev coming soon
=> fix: Updates to invoke service and invoke plugin [targeting Neeraj's branch]

src/plugins/apim/azureApimFunctionPlugin.ts, src/plugins/apim/azureApimServicePlugin.ts, src/plugins/azureBasePlugin.test.ts, src/plugins/azureBasePlugin.ts, src/plugins/deploy/azureDeployPlugin.ts, src/plugins/func/azureFuncPlugin.ts, src/plugins/invoke/azureInvokePlugin.ts, src/plugins/login/azureLoginPlugin.ts, src/plugins/logs/azureLogsPlugin.ts, src/plugins/offline/azureOfflinePlugin.ts, src/plugins/package/azurePackagePlugin.test.ts, src/plugins/package/azurePackagePlugin.ts, src/plugins/remove/azureRemovePlugin.ts, src/plugins/rollback/azureRollbackPlugin.ts
Allows base plugin to access options and adds helper function `getOption` for all plugins to use
=> feat: Add options to base plugin class

package.json
- Adds npm script to generate service principal
=> feat: Adds NPM script to generate service principal

pipelines/ci.yml, scripts/build.sh
Simple CI check to start moving repo to Azure Devops. Will add release pipelines and scripts in future PR.
Resolves [AB#588]
=> feat: Azure Pipelines CI pipeline & script

README.md, docs/examples/apim.md
Simple example of configuring APIM with `serverless.yml`.
Resolves [AB#496]
=> feat: APIM example doc

package-lock.json, package.json, src/services/armService.test.ts, src/services/armService.ts, src/services/baseService.ts, src/services/loginService.test.ts, src/services/resourceService.test.ts, src/services/resourceService.ts, src/test/mockFactory.ts
This checks the previously deployed template (including parameters/values) to see if the generated template has changed since the last deployment. If it has not changed, it will not deploy the ARM template. Since many cases will be code changes, this will drastically increase the speed of the average deployment.
Resolves [AB#789]
=> perf: Short-circuit deployment if ARM template hasn't changed

pipelines/templates/unit-tests.yml
unit test pipeline was swalling error
=> ci: exit pipeline when there's error

src/services/functionAppService.test.ts, src/services/functionAppService.ts
Many times, especially when deploying a service for the first time, there is a considerable amount of time before the function app is ready and provisioned. In my experimenting, every single time, the app has failed before finishing. This increases the amount of time between each retry, and tells the user which number of retry they are on in the log
=> feat: Wait longer for deploying a function app

src/plugins/apim/azureApimPlugin.ts, src/plugins/deploy/azureDeployPlugin.test.ts, src/plugins/deploy/azureDeployPlugin.ts
=> fix: Move deploy apim command to deploy plugin

src/armTemplates/compositeArmTemplate.ts, src/armTemplates/resources/apim.ts, src/armTemplates/resources/appInsights.ts, src/armTemplates/resources/appServicePlan.ts, src/armTemplates/resources/functionApp.ts, src/armTemplates/resources/hostingEnvironment.ts, src/armTemplates/resources/storageAccount.ts, src/armTemplates/resources/virtualNetwork.ts, src/models/armTemplates.ts, src/services/armService.test.ts, src/services/armService.ts
=> fix: Exclude ARM params with null values

src/armTemplates/resources/functionApp.ts, src/config.ts, src/plugins/azureBasePlugin.ts, src/plugins/login/utils/simpleFileTokenCache.test.ts, src/plugins/package/azurePackagePlugin.ts, src/services/baseService.test.ts, src/services/funcService.test.ts, src/services/functionAppService.test.ts, src/services/functionAppService.ts, src/services/offlineService.test.ts, src/services/packageService.test.ts, src/services/publishService.test.ts, src/services/publishService.ts, src/services/rollbackService.test.ts
This is a PR addressing @wbreza's feedback on [previous PR](https://github.com/serverless/serverless-azure-functions/pull/362). I figured the changes were big enough to separate the 2 and make it easier to see.
=> fix: Publish Service to handle Function App publishing

src/config.ts, src/services/offlineService.test.ts, src/services/packageService.ts, src/shared/bindings.json, src/shared/bindings.test.ts, src/shared/bindings.ts, src/shared/utils.test.ts, src/shared/utils.ts
Fetch `bindings.json` from [Azure Functions template repo](https://github.com/Azure/azure-functions-templates)
Closes #15 
Simple GET request to fetch the JSON object from the master branch of the GitHub repo. Still need to write tests to verify. Will mock out actual axios request in tests.
**_Is this ready for review?:_** YES 
=> feat: Fetch bindings.json from official Azure Functions repo

src/services/armService.test.ts, src/services/armService.ts
Closes #410 
Checked if params were undefined, return empty object if they are.
Redeploy a function app that previously had no parameters. It used to be broken, now it's not :)
**_Is this ready for review?:_** YES 
=> fix: Hot fix for undefined params

jest.config.js, src/plugins/apim/azureApimPlugin.ts, src/plugins/deploy/azureDeployPlugin.ts, src/plugins/func/azureFuncPlugin.test.ts, src/plugins/login/azureLoginPlugin.ts, src/plugins/login/utils/simpleFileTokenCache.test.ts, src/plugins/login/utils/simpleFileTokenCache.ts, src/services/armService.ts, src/services/funcService.test.ts, src/services/funcService.ts, src/services/functionAppService.test.ts, src/services/functionAppService.ts, src/services/invokeService.test.ts, src/services/invokeService.ts, src/services/packageService.ts
- Add tests for missing coverage of `simpleFileTokenCache`
- Rename `sls.cli.log` calls to `this.log` where possible
- Added missing tests for `invokeService` and `functionAppService`
- Updated `jest.config.js` to actually ignore files within `test` folder for coverage
=> test: Additional test coverage & general cleanup

.dependabot/config.yml, pipelines/templates/unit-tests.yml
1. Updating old Mac & Windows agent as they're being [removed on 3/23](https://devblogs.microsoft.com/devops/removing-older-images-in-azure-pipelines-hosted-pools/)
2. add dependabot config so it target `dev` instead of `master
* Update pipelines to use new agents
=> Upgrade windows & mac agents per AzDO removing older agents support

src/armTemplates/resources/functionApp.ts, src/services/configService.test.ts, src/services/functionAppService.test.ts, src/services/functionAppService.ts
=> Update API endpoint to work with linux

package-lock.json, package.json
Hotfix - Update version of Azure Functions Core tools
=> fix: Update version of Azure Functions Core tools

src/armTemplates/resources/appServicePlan.test.ts, src/armTemplates/resources/appServicePlan.ts, src/armTemplates/resources/functionApp.test.ts, src/armTemplates/resources/functionApp.ts
Small update to move `reserved` property from site resource to app service plan resource.
Closes #437 
See above.
Deploy a premium node linux function app. It shouldn't fail
=> fix: Move reserved prop to App Service Plan

README.md, src/plugins/remove/azureRemovePlugin.test.ts, src/plugins/remove/azureRemovePlugin.ts
Added `--force` option with remove command. Allows for automation of removal.
Closes #422 
- Added `--force` option in `removePlugin`
- Check for valid user input or `--force` before deleting resource group
Run `sls remove --force`. Your resource group will be removed.
=> feat: Remove --force command

docs/DEPLOY.md
Closes #396
add statement about specifying storage account
Could you check if my understanding is correct?
=> fix: Specifying storage account name

src/shared/bindings.json
Closes #430
I think i provided appropriate info in #430 about the issue itself, and the change is self explanatory.
Is this ready for review?: YES
Is it a breaking change?: NO
Sorry for the new pr but it was just easier to cherry pick the change to my dev branch :)
(Original conversations can be found in the other [PR](https://github.com/serverless/serverless-azure-functions/pull/431))
=> fix: adding cosmosDBIn as an accepted trigger

src/services/functionAppService.test.ts, src/services/functionAppService.ts, src/services/invokeService.test.ts, src/services/invokeService.ts, src/shared/bindings.ts
Print response message from failed axios request in invoke plugin
Catch the error message from failed axios request and log message
Invoke API incorrectly (try a service that hasn't been deployed, should get 404). Error message will be printed.
=> fix: Print error message for invoke command

README.md, docs/CONFIG.md
Update documentation in README and CONFIG
=> docs: Update README and CONFIG docs

integrationTests/tests/deploy.clvr.ts, src/services/functionAppService.ts
- Update integration tests to use GA version of package instead of beta.
- Small fix of not printing request options
- Changed `beta` to `latest`
- Removed log statement for printing request options
=> ci: Update package install target

examples/typescript-webpack/.gitignore, examples/typescript-webpack/host.json, examples/typescript-webpack/package-lock.json, examples/typescript-webpack/package.json, examples/typescript-webpack/serverless.yml, examples/typescript-webpack/src/func1.ts, examples/typescript-webpack/src/func2.ts, examples/typescript-webpack/tsconfig.json, examples/typescript-webpack/webpack.config.js, src/plugins/offline/azureOfflinePlugin.test.ts, src/plugins/offline/azureOfflinePlugin.ts, src/services/configService.ts, src/services/offlineService.ts, src/services/packageService.ts, src/shared/utils.ts
Use webpack output files (if exists) on offline command
Closes https://github.com/serverless/serverless-azure-functions/issues/392 https://github.com/serverless/serverless-azure-functions/issues/366
`serverless-webpack` have a trigger on `before:offline:start`, So I changed offline hook so we will have `offline:start` hook.
Also, change the generated `function.json` `scriptFile` property to point to `.webpack` folder
Everything should work the same as before, just when running offline command webpack plugin (if exists) will compile the files 
```
cd examples/typescript-webpack
npm install
npm run offline
```
You should see the error:
This is the current behavior.
To fix it we need to link the new version of the library.
go to the root directory and run `npm link`
then go back to the …
=> fix: use webpack output files on offline command

examples/typescript-webpack/package-lock.json, examples/typescript-webpack/package.json
Just update the lib version so the example will work
related to the last PR: https://github.com/serverless/serverless-azure-functions/pull/472
**_Is this ready for review?:_** YES 
=> chore: update serverless-azure-functions in typescript-webpack example

integrationTests/configurations/dotnet22-linux/serverless.yml, integrationTests/configurations/dotnet22-windows/serverless.yml, integrationTests/configurations/dotnet31-linux/serverless.yml, integrationTests/configurations/dotnet31-windows/serverless.yml, integrationTests/configurations/node10-linux-external/serverless.yml, integrationTests/configurations/node10-linux/serverless.yml, integrationTests/configurations/node10-windows-webpack/serverless.yml, integrationTests/configurations/node10-windows/serverless.yml, integrationTests/configurations/node12-linux-external/serverless.yml, integrationTests/configurations/node12-linux/serverless.yml, integrationTests/configurations/node12-windows-premium/serverless.yml, integrationTests/configurations/node12-windows-webpack/serverless.yml, integrationTests/configurations/node12-windows/serverless.yml, integrationTests/configurations/python36-premium/serverless.yml, integrationTests/configurations/python36/serverless.yml, integrationTests/configurations/python37/serverless.yml, integrationTests/configurations/python38/serverless.yml
Change the prefix of all configurations for integration tests to `int`
=> test: Update prefix of integration test configurations

README.md, package-lock.json, src/config/runtime.test.ts, src/config/runtime.ts, src/services/configService.test.ts
Closes #536 
On `src/config/runtime.ts` file:
In **Runtime** enum:
```typescript
export enum Runtime {
NODE10 = "nodejs10",
NODE12 = "nodejs12",
NODE14 = "nodejs14",    👈 Added
PYTHON36 = "python3.6",
PYTHON37 = "python3.7",
PYTHON38 = "python3.8",
DOTNET22 = "dotnet2.2",
DOTNET31 = "dotnet3.1",
}
```
In **supportedRuntimes** array
```typescript
export const supportedRuntimes = [
Runtime.NODE10,
Runtime.NODE12,
Runtime.NODE14,    👈 Added
Runtime.PYTHON36,
Runtime.PYTHON37,
Runtime.PYTHON38,
Runtime.DOTNET22,
Runtime.DOTNET31
]
```
In `dockerImages` map
```typescript
export const dockerImages = {
nodejs10: "NODE|10",
nodejs12: "NODE|12",
nodejs14: "NODE|14",    👈 Added
"python3.6": "PYTHON|3.6",
"python3.7": "PYTHON|3.7",
"python3.8": "PYTHON|3.8",
"dotnet3.1": "DOTNET|3.1",
}
``` …
=> Add Node.js 14

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
This pull request fixes some typos in the GitHub issue and pull request templates.
=> docs: Fix typos in GitHub templates

package-lock.json, package.json
Closes #654 
Updated package version number to 2.2.0
=> Release v2.2.0 with node 16 and 18 support

package-lock.json, package.json
Release v2.2.1 after fixing publishing script
=> chore: Release v2.2.1
