deploy/lib/createFunction.js
deploy/lib/createFunctions.js
provider/azureProvider.js

Work around for kudu sync triggers issue

---

provider/azureProvider.js

This PR addresses two limitations with the way the `invoke` command currently handles function parameters:
1. It adds support for specifying the JSON config as a string literal (via the `-d` flag), in addition to the file-based support (via the `-p` flag).   
```shell
serverless invoke -f hello -d '{"name":"JC"}'
```
2. It adds support for specifying multiple parameters (properties) in the provided JSON config (inline or file). Otherwise, `invoke` would only send the last parameter to the function invocation.
Some of the churn in the PR is related to formatting, which I did to improve the code folding support in VS Code (or other editors that rely on indentation).

Invoke enhancements

---

deploy/azureDeploy.js
deploy/azureDeployFunction.js
index.js
invoke/azureInvoke.js
logs/azureLogs.js
provider/azureProvider.js
remove/azureRemove.js

This is a fix for Issue #53 
The constructor for the AzureProvider performs initialisation of variables used later in the process, however this constructor is called before the Serverless framework has initialised all of the variables from the `serverless.yml` file.
This change moves the initialisation process to each command to perform as a first step.

Fix for Issue #53

---

provider/armTemplates/azuredeploy.json
provider/armTemplates/azuredeployWithGit.json
provider/azureProvider.js

This PR updates the existing ARM deployment templates, to create an App Insights instance, and bind the functions to it. This way, devs can deploy their functions, invoke them, etc. and then begin to monitor them without needing to do anything extra to set this up. Since App Insights provides a pretty permissive free-tier (1 GB data/month), it seems reasonable to create this resource by default.
Some questions to discuss around the design of this feature:

Adding App Insights support

---

README.md
package.json
provider/azureProvider.js
remove/lib/deleteResourceGroup.js
shared/loginToAzure.js

This PR introduces an interactive login experience (using the `az-login` component I'm working on), that allows devs to deploy/manage their Azure functions, without needing to explicitly create a service principal and then set the four env vars. This results in a simpler, less error-prone getting started experience. Additionally, this PR results in more code being removed, then added, which is always nice :)
With this change, if those env vars are set, then they will continue to be used (although it also supports the same env vars as Terraform as well, for increased interop). However, if they aren't set, then the CLI will initiate an interactive login by launching the user's default browser to the device login page (`https://aka.ms/devicelogin`), and copying the device code to the …

Adding an interactive login experience

---

.eslintrc.json
.gitignore
config.js
deploy/lib/CreateResourceGroupAndFunctionApp.js
deploy/lib/createFunction.js
deploy/lib/createFunctions.js
invoke/azureInvoke.js
invoke/lib/invokeFunction.js
logs/lib/retrieveLogs.js
package-lock.json
package.json
provider/azureProvider.js
shared/parseBindings.js
shared/utils.js

Alright, this looks intimidating, but I swear it's not. :)
To test this, create a serverless app and install the plugin from my fork via
`$ npm install fiveisprime/serverless-azure-functions` then run through the
various commands. You may run into DNS issues when removing/recreating,
which is already a tracked issue (it's much further down the stack yo).
Updated to the latest version of az-login to fix the error handling for failed
login attempts.
Added ESLint test command, cleaned up all existing lint issues, and cleaned up
some confusing/unused code. Normalized the HTTP request usage so they all use the
request module rather than some using the https module.
run `$ npm test` to run the lint (please do this before committing).
Changed the invoke command to no longer require logging in to …

Add lint, simplify some code, add error handling.

---

provider/azureProvider.js

Was: `Serverless: Uploading pacakge.json...`
Now: `Serverless: Uploading package.json...`

Fix typo in console output when uploading package.json

---

provider/azureProvider.js

This PR addresses #44 and #106 by allowing you to configure `resourceGroup` and 
`deploymentName` in `serverless.yml`.
```
provider:
name: azure
resourceGroup: your-resource-group
deploymentName: your-deployment-name
```
We have been using this fork in production for several weeks with no issues.

Update provider to allow configuring resource group

---

package-lock.json
src/config.ts
src/plugins/deploy/azureDeployPlugin.ts
src/provider/armTemplates/azuredeploy.json
src/services/functionAppService.ts

1. use the current Azure recommended zip deploy method to [run function from deployment package ](https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package)
1. remove support for individual function deploy since that's not supported by zipdeploy

 feature: change to zipdeploy & run from package

---

package-lock.json
src/index.test.ts
src/index.ts
src/test/mockFactory.ts

test: Unit tests for Azure Index

---

package-lock.json
package.json
src/plugins/func/azureFunc.test.ts
src/plugins/func/funcUtils.ts
src/plugins/package/azurePackage.test.ts
src/plugins/package/azurePackage.ts
src/services/apimService.test.ts
src/services/baseService.test.ts
src/services/baseService.ts
src/services/functionAppService.test.ts
src/shared/binding.test.ts
src/shared/bindings.ts
src/shared/utils.test.ts
src/shared/utils.ts
src/test/mockFactory.ts

- Updates packaging strategy to write function.json into expected folder structure
- Dynamically resolves handler path based on yaml definition and destination folder
- Removes and cleans up function.json and function folders after packaging is completed
Resolves ABA#82, 90, 89

feat: Azure Packaging updates

---

src/armTemplates/resources/appInsights.ts
src/armTemplates/resources/hostingEnvironment.ts
src/armTemplates/resources/virtualNetwork.ts
src/services/functionAppService.test.ts
src/services/functionAppService.ts

The SCM domain is different based on the type of function app deployment.  In a typical function app, the SCM domain is always {appName}.scm.azurewebsites.net.
When deploying a function into an App Service Environment (ASE) the SCM domain is a sub domain off of the ASE, ex) {appName}.scm.{asePath}.p.azurewebsites.net
This fix addresses the difference in finding the correct SCM domain to deploy the zip package.

fix: Ensures the correct SCM domain is found for uploading zip package

---

src/services/functionAppService.test.ts

Discovered this small bug in the test. Overloading the variable name `masterKey`, using `result` instead.

fix: Simple fix in test of equality comparison

---

.editorconfig
package-lock.json
src/models/serverless.ts
src/plugins/deploy/azureDeployPlugin.ts
src/services/armService.test.ts
src/services/armService.ts
src/services/baseService.test.ts
src/services/baseService.ts
src/services/functionAppService.ts

when a name is specified in cli or yaml, serverless will use this name to create the resourceGroup instead of creating a name from convention. 
all underlying resources will still be created with a convention name.

feat: add support for specifying resourceGroup in both cli and yaml

---

package-lock.json
src/armTemplates/resources/functionApp.ts
src/config.ts
src/index.ts
src/models/serverless.ts
src/plugins/deploy/azureDeployPlugin.test.ts
src/plugins/deploy/azureDeployPlugin.ts
src/plugins/login/loginPlugin.ts
src/plugins/rollback/azureRollbackPlugin.test.ts
src/plugins/rollback/azureRollbackPlugin.ts
src/services/armService.ts
src/services/azureBlobStorageService.test.ts
src/services/azureBlobStorageService.ts
src/services/baseService.ts
src/services/functionAppService.test.ts
src/services/functionAppService.ts
src/services/resourceService.test.ts
src/services/resourceService.ts
src/services/rollbackService.test.ts
src/services/rollbackService.ts
src/shared/utils.test.ts
src/shared/utils.ts
src/test/mockFactory.ts

- Adds new `rollback` plugin
- Fixes `deploy list` to show actual timestamp from name, which is used for rollback
- Adds required functionality to `AzureBlobStorageService` and `ArmService`
- Adds previously missing tests of required functionality
1. Get a timestamp. Use
```
sls deploy list
```
to retrieve one.
2. Roll back function app to timestamp
```
sls rollback -t <timestamp>
```
In `deploy` section of `serverless.yml`, you can specify whether to run from a blob URL or deploy the package directly to the function app by setting:
```yaml
deploy:
runFromBlobUrl: true|false
```
Resolves [AB#317]

feat: Rollback Plugin

---

src/services/functionAppService.ts

Remove forgotten `await` statement before using `Promise.all`

fix: Remove await statement from Promise.all

---

README.md

Update README to reflect current state of plugin.
[AB#483]

docs: README Update

---

src/plugins/azureBasePlugin.ts
src/plugins/deploy/azureDeployPlugin.ts
src/plugins/login/azureLoginPlugin.test.ts
src/plugins/login/azureLoginPlugin.ts
src/services/loginService.ts

Added feature to specify subscription ID in the CLI which overrides any existing subscriptions ID and deploys the functions to the subscription specified by the user.
```bash
sls deploy -i <subscriptionID>
```
AB#360

feat: Added feature to specify Azure subcription ID in CLI before deployment

---

src/plugins/deploy/azureDeployPlugin.test.ts
src/plugins/deploy/azureDeployPlugin.ts
src/services/resourceService.test.ts
src/services/resourceService.ts
src/services/rollbackService.test.ts
src/services/rollbackService.ts

Rollback requires a timestamp. Rather than forcing users to run `sls deploy list` to generate the deployments they can choose from, `sls rollback` with no args also generates the same list.
Resolves [AB#493]

feat: List deployments for rollback when no timestamp given

---

src/plugins/login/azureLoginPlugin.test.ts
src/plugins/login/azureLoginPlugin.ts
src/plugins/login/loginHooks.ts

Rather than changing the `AzureLoginPlugin` to add `"before:new:hook": this.login.bind(this)` every time a new hook is added that needs authentication, this allows for the hooks (without `before:`) to be placed in a separate file. These are loaded in the constructor of the plugin, which sets up the proper hooks.

refactor: Moved hooks requiring login to separate file

---

package-lock.json
package.json
src/services/apimService.test.ts
src/services/apimService.ts
src/test/mockFactory.ts

When generating an APIM resource name, the service now
uses the shortened resource name, consistent with other resources.

fix: apim uses shortened region names

---

src/plugins/login/azureLoginPlugin.test.ts
src/plugins/login/azureLoginPlugin.ts

New PR created because of merge issues due to one unsigned commit. 
#AB360

feat: specify subscription ID in serverless yaml

---

src/models/serverless.ts
src/plugins/package/azurePackagePlugin.ts
src/services/baseService.ts
src/services/offlineService.ts
src/services/packageService.test.ts
src/services/packageService.ts
src/shared/utils.test.ts
src/shared/utils.ts
src/test/mockFactory.ts

In serverless.yml, you can now specify an API route within `x-azure-settings`, which will be added to the `function.json` file.
Resolves [AB#552]

feat: Path from x-azure-settings is included in function.json

---

src/services/apimService.ts
src/services/functionAppService.ts
src/shared/utils.test.ts
src/shared/utils.ts

When listing the deployed functions on 1st time deployment it may take some additional time to initialize the function app and extract the functions.  This adds a retry policy that will retry the function listing multiple times until the function app is fully ready.

fix: Add retry support when listing deployed functions

---

src/services/offlineService.test.ts
src/services/offlineService.ts

Not able to repro `ENOENT` error yet, but this PR should help with debugging.
See [this stack overflow answer](https://stackoverflow.com/a/27688805) for more details.

fix: Inject current environment variables to spawn process

---

src/plugins/offline/azureOfflinePlugin.ts
src/services/offlineService.test.ts
src/services/offlineService.ts

Cleans up offline files when user interrupts offline process. Allows user to skip cleanup with CLI option.

feat: Handle SIGINT and cleanup offline files unless specified to skip

---

package-lock.json
src/plugins/login/azureLoginPlugin.test.ts
src/plugins/login/azureLoginPlugin.ts
src/plugins/login/utils/simpleFileTokenCache.test.ts
src/plugins/login/utils/simpleFileTokenCache.ts
src/services/baseService.ts
src/services/functionAppService.test.ts
src/services/functionAppService.ts
src/services/loginService.test.ts
src/services/loginService.ts
src/test/mockFactory.ts

feat: Cache interactive login credentials
Currently once a user logs in using the interactive login, there is no way to cache the credentials and the user must keep logging in through that method. This adds a simple file token cache that saves the credentials and subscription information and then uses those to login, reducing number of logins required. 
AB#359

feat: Cache interactive login credentials

---

src/plugins/login/loginHooks.ts

fix: Don't require login during packaging. 
Logging into the cloud provider takes time and is not necessary before all operations. We currently had the plugin logging into Azure, even when just packaging, which isn't necessary. This prevents login from being called when it is not needed.
AB#801

fix: Don't require login during packaging. 

---

docs/DEPLOY.md
src/config.ts
src/models/serverless.ts
src/plugins/login/azureLoginPlugin.test.ts
src/services/baseService.ts
src/services/functionAppService.test.ts
src/services/functionAppService.ts
src/services/rollbackService.test.ts

feat: Deploy function app code from blob storage URL

---

pipelines/publish-prerelease.yml
pipelines/publish-release.yml
scripts/publish.sh
scripts/version.sh

Pipelines for release and pre-release on merges to master and dev respectively. Dev branch will release a beta to NPM and Master will release a patch to NPM
**Pipelines not set up yet - still need approval from serverless org to run Azure DevOps on the repo**
Resolves [AB#588]

feat: Release and pre-release pipelines with publish script

---

src/plugins/deploy/azureDeployPlugin.test.ts
src/plugins/deploy/azureDeployPlugin.ts

With `package.individually` the expected function app zip file is not generated in form supported by a plugin.
In such case currently plugin just logs some error message as follows:
```
Function app zip file '/Users/medikoo/Projects/tests/serverless-azure/.serverless/test-azure-0x.zip' does not exist
```
but doesn't exit with an error, which gives a confusing impression.
This PR ensures that such scenario is reported with plugin error

fix: Crash deployment if function app zip file doesn't exist

---

src/services/functionAppService.test.ts
src/services/functionAppService.ts
src/services/loginService.test.ts

Quick fix for not uploading zipped code to Function App if configured to only run from blob, and vice versa

perf: Skip upload to function app if configured to run from blob

---

src/plugins/login/azureLoginPlugin.test.ts
src/plugins/login/azureLoginPlugin.ts

I think plugin should not exit process abruptly. Technically it leaves Framework stopped without any possibility to do cleanup (e.g. send some statistics info).
Additionally Framework implements error reporting in user friendly way, so I believe it's better to just let the error surface, and let Framework pick it.

Let Serverless Framework handle error

---

src/plugins/login/utils/simpleFileTokenCache.test.ts
src/plugins/login/utils/simpleFileTokenCache.ts

This issue surfaced when trying to do interactive login. It seems like the file was created, but was either invalid or empty. This adds a couple checks to make sure the JSON is parsed correctly and that all the data exists.
Resolves AB#838

fix: Fix bug with invalid token file for interactive login

---

src/models/serverless.ts
src/plugins/apim/azureApimFunctionPlugin.ts
src/plugins/apim/azureApimServicePlugin.ts
src/plugins/azureBasePlugin.ts
src/plugins/deploy/azureDeployPlugin.ts
src/plugins/func/azureFuncPlugin.ts
src/plugins/invoke/azureInvokePlugin.ts
src/plugins/login/azureLoginPlugin.ts
src/plugins/logs/azureLogsPlugin.ts
src/plugins/offline/azureOfflinePlugin.ts
src/plugins/package/azurePackagePlugin.ts
src/plugins/remove/azureRemovePlugin.ts
src/plugins/rollback/azureRollbackPlugin.ts

feat: Add `hooks` type to base plugin, document plugin options for CLI help

---

tsconfig.json

Excluding all test files from ./lib/. These will no longer be included in the NPM package.
AB#804

fix: exclude test files

---

src/plugins/login/utils/simpleFileTokenCache.test.ts
src/plugins/login/utils/simpleFileTokenCache.ts

Fails if user previously started interactive login process without finishing because it writes an invalid JSON file. This checks to make sure the parsed JSON is valid and that entries exists

fix: Check for valid entries in token cache remove and find

---

src/models/armTemplates.ts
src/services/armService.test.ts
src/services/resourceService.ts
src/test/mockFactory.ts

Currently, if a deployment fails and the next deployment's template & parameters are identical, the deployment will be skipped. This adds the check to see if the deployment was successful.
Resolves AB#852

fix: Don't skip deploy if previous equivalent deployment failed

---

src/services/offlineService.test.ts
src/services/offlineService.ts

Fixes issue of removing `local.settings.json` in offline cleanup. There might be project sensitive information there, and it would be inconvenient for the developer if that were removed.
Resolves AB#929

fix: Don't remove local.settings.json in offline cleanup

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md

Add contribution guidelines and templates for pull requests, bug reports, and feature requests for the  plugin repo. Most of the templates and guides are taken from the core Serverless repo to best match the process put forth there, with minor adjustments to reflect the setup of this repo 
AB#805

docs: Add contribution guidelines

---

src/models/serverless.ts
src/plugins/azureBasePlugin.ts
src/plugins/package/azurePackagePlugin.test.ts
src/plugins/package/azurePackagePlugin.ts

Because Azure Functions does not support individually packaged functions, the plugin needs to throw an error when user tries to perform the operation.
Resolves #254

fix: Throw error if user tries to specify package.individually

---

src/models/serverless.ts
src/services/baseService.test.ts
src/services/baseService.ts
src/services/namingService.ts

Fixes a regression in accepting `region` and `stage` options from CLI to form resource group name. Adds acceptance of `prefix` as well. Does so by configuring each of them in `serverless.service` (`ServerlessAzureConfig`) as one of the first steps of the `BaseService` constructor.
Also puts `location` into `region` inside the config if `location` is specified, but `region` is not.
Resolves #280, #282 and #281

fix: Use stage, region, resourceGroup and prefix from CLI options

---

src/armTemplates/resources/appServicePlan.ts
src/armTemplates/resources/functionApp.ts

When the "name" of appServicePlan and functionApp is filled in the template, the resource created or updated have the wrong name.
see #292

fix appServicePlan name and functionApp name

---

src/models/serverless.ts
src/plugins/login/azureLoginPlugin.test.ts
src/plugins/login/azureLoginPlugin.ts
src/services/baseService.test.ts
src/services/baseService.ts

refactor: Move subscriptionId logic to BaseService

---

src/services/rollbackService.test.ts
src/services/rollbackService.ts
src/test/mockFactory.ts

Remove the downloaded artifact from `.serverless` after deployed to service
Resolves #287

fix: Clean up downloaded artifact after rollback

---

package-lock.json
src/plugins/login/azureLoginPlugin.test.ts
src/plugins/login/azureLoginPlugin.ts
src/services/azureBlobStorageService.test.ts
src/services/azureBlobStorageService.ts
src/services/loginService.test.ts
src/services/loginService.ts

Checks to see if subscription ID is already specified before throwing error message for empty subscription array from an authentication result.
Apparently when a service principal authenticates, there are no subscriptions in the returned array.

fix: Don't throw error if subscription ID already specified

---

src/services/rollbackService.test.ts
src/services/rollbackService.ts

Strings were being logged out of order at random for some reason. Seemed cleaner anyway to just combine them into one string and adjusted tests.

fix: Combine rollback log statement into one string

---

src/services/functionAppService.ts

Logs the name of the function app as defined from the `FunctionAppResource` rather than the service name.
Resolves #302

fix: Log correct function app name in deployment

---

src/models/azureProvider.ts
src/services/armService.test.ts
src/services/armService.ts

Logs a more detailed error message when an ARM template deployment fails:

feat: More detailed error message upon ARM deployment failure

---

src/services/baseService.test.ts
src/services/baseService.ts

The key for Azure Region moved from `location` to `region`. This just adds backwards compatibility so that the value from `location` is stored in the `region` config if no other is specified.
Resolves #280

fix: Add backwards compatibility for location/region keys in config

---

src/index.test.ts
src/plugins/func/azureFuncPlugin.ts
src/plugins/invoke/azureInvokePlugin.ts
src/plugins/offline/azureOfflinePlugin.ts
src/plugins/package/azurePackagePlugin.ts
src/services/baseService.ts

Fixes error we found in testing serverless optional variables (`${opt:stage, 'dev'}`), which allow you to specify a param at deploy time, as well as a default value. Also fixes potentially more serious problems with setting names before the configuration is initialized.

fix: Move service initialization outside of plugins

---

README.md
scripts/generate-service-principal.sh
src/models/azureProvider.ts
src/plugins/login/azureLoginPlugin.test.ts
src/services/baseService.test.ts
src/services/baseService.ts
src/services/loginService.test.ts
src/services/loginService.ts
src/test/mockFactory.ts

Updates Azure Service Principal naming convention.
Will need to update Azure Pipelines before merging this change.

refactor: Update service principal env variable names

---

src/armTemplates/resources/apim.test.ts
src/armTemplates/resources/apim.ts
src/armTemplates/resources/appInsights.test.ts
src/armTemplates/resources/appInsights.ts
src/armTemplates/resources/appServicePlan.test.ts
src/armTemplates/resources/appServicePlan.ts
src/armTemplates/resources/functionApp.test.ts
src/armTemplates/resources/functionApp.ts
src/armTemplates/resources/hostingEnvironment.test.ts
src/armTemplates/resources/hostingEnvironment.ts
src/armTemplates/resources/storageAccount.test.ts
src/armTemplates/resources/storageAccount.ts
src/armTemplates/resources/virtualNetwork.test.ts
src/armTemplates/resources/virtualNetwork.ts
src/services/baseService.ts
src/services/namingService.test.ts
src/services/namingService.ts

fix: add resource group name hash to resource names
Azure has naming requirements for resources, and for some, requires the names to be unique across azure. Currently on deployments, the plugin doesn't add a more unique hash to the name, so it is possible collisions can occur. By adding the resource group name hash to the resource name, we can avoid this.
AB#1002

fix: add resource group name hash to resource names

---

src/armTemplates/compositeArmTemplate.ts
src/armTemplates/resources/apim.ts
src/armTemplates/resources/appInsights.ts
src/armTemplates/resources/appServicePlan.ts
src/armTemplates/resources/functionApp.ts
src/armTemplates/resources/hostingEnvironment.ts
src/armTemplates/resources/storageAccount.ts
src/armTemplates/resources/virtualNetwork.ts
src/models/armTemplates.ts
src/models/serverless.ts
src/services/armService.test.ts
src/services/armService.ts
src/services/azureKeyVaultService.test.ts
src/services/azureKeyVaultService.ts
src/services/rollbackService.test.ts
src/services/rollbackService.ts
src/test/mockFactory.ts

Resolves issue of not being able to skip previous deployments due to `identity` as well as mismatch in casing of `type` within ARM parameters

fix: Fix regression of skipping identical ARM deployment

---

src/services/offlineService.test.ts
src/services/offlineService.ts

No longer require users to have `azure-functions-core-tools` globally installed to run `sls offline`.
Closes #319

fix: Invoke offline without requiring global install

---

src/services/armService.test.ts
src/services/armService.ts
src/services/resourceService.ts

If a first-time deployment fails, it will crash with a weird error because the last deployment is undefined. This handles that scenario.

fix: Throw original error if no previous deployments

---

src/plugins/login/utils/simpleFileTokenCache.test.ts

Getting original `os.homedir`, setting it to a mock, and then manually restoring after the test is finished.

fix: Mock home directory in test

---

README.md
src/plugins/invoke/azureInvokePlugin.test.ts
src/plugins/invoke/azureInvokePlugin.ts

Moves data path initialization outside of the constructor and does not replace the `data` property within options. Instead, passes the contents of the file path to the invoke service.
Fixes #320

fix: Fix failing invoke with data path

---

src/plugins/login/utils/simpleFileTokenCache.test.ts
src/plugins/login/utils/simpleFileTokenCache.ts
src/services/azureKeyVaultService.test.ts

fix: Create default .azure directory if not present
The pluging currently saves credentials from interactive login in the .azure directory by default. If the user doesn't have a .azure directory, current;y the plugin hits an error. This fix checks to make sure the .azure directory exists and creates it if not. 
Closes #317

fix: Create default .azure directory if not present

---

.vscode/launch.json
package.json
src/config.ts
src/models/serverless.ts
src/services/apimService.test.ts
src/services/baseService.test.ts
src/services/baseService.ts
src/services/configService.test.ts
src/services/configService.ts
src/services/funcService.ts
src/services/functionAppService.ts
src/services/invokeService.test.ts
src/services/invokeService.ts
src/services/loginService.ts
src/services/packageService.ts
src/services/resourceService.ts
src/services/rollbackService.ts
src/shared/constants.ts

`ConfigService` and its usage. This removes the configuration logic from `BaseService` and keeps it all in one place. Also adds some constants for default configuration.
In a future PR, the `ConfigService` will cache its configuration so that the service is only configured one time in the initialization of the first `BaseService` subclass. It will store the data in the `serverless.variables` object and checks to see if that value is populated on future runs.
Also added some constants for default configuration values.
Removed the configuration logic from the `BaseService` and placed inside the `ConfigService`, which is initialized in the constructor of the `BaseService`
- Unit tests
- Run an end-to-end deployment of a service
_**Note: Run `npm run test:ci` to run all validation checks on …

feat: ConfigService for centralizing configuration and simplifying BaseService

---

src/config.ts
src/models/serverless.ts
src/services/apimService.ts
src/services/baseService.ts
src/services/configService.test.ts
src/services/configService.ts
src/services/functionAppService.test.ts
src/services/functionAppService.ts
src/services/packageService.ts
src/services/rollbackService.test.ts
src/services/rollbackService.ts
src/shared/utils.ts

Fix updating of function app settings (SDK call wasn't working) and syncing triggers for function apps running from external package.
- Updated the `syncTriggers` function to use [the correct URL](https://docs.microsoft.com/en-us/azure/azure-functions/functions-deployment-technologies#trigger-syncing)
- Updated the `updateFunctionAppSetting` function to just make a rest API call instead of using the SDK. The SDK call now gives the error message: `Error: Failed to update function app settings: Error: {"Code":"BadRequest","Message":"SiteAppSettings object is not present in the request body...`. I checked with the documentation and found matching GitHub issues. Rather than the SDK call, just making a REST request according to [the docs](https://docs.microsoft.com/en-us/rest/api/appservice/web …

fix: Sync triggers on external package deployment

---

pipelines/ci.yml
pipelines/templates/unit-tests.yml

Hosted agent roll out a fix that broke our builds:
1. Previously, npm wasn’t getting packaged with the version of node in the tool cache,
ie. npm 5.6.0 should be used alongside Node 8.10.0.
1. The fix is to pin to a later version of Node 8 (e.g. 8.16.1) which comes with npm 6+
- https://nodejs.org/en/download/releases/.
* This will probably slow the build down a little bit since the agent will have to download
the version (instead of it being pre-installed), but we'll get the right version of npm for free.
Closes #344  …

ci: fix failing Node 8 builds on windows agent

---

src/armTemplates/resources/apim.ts
src/armTemplates/resources/appInsights.ts
src/armTemplates/resources/appServicePlan.ts
src/armTemplates/resources/functionApp.ts
src/armTemplates/resources/hostingEnvironment.ts
src/armTemplates/resources/storageAccount.ts
src/armTemplates/resources/virtualNetwork.ts
src/models/armTemplates.ts

Fixed mismatched ARM parameter names and spelling errors. Added interfaces for all resource ARM parameters to prevent future occurrence.
- Fixed spelling errors
- Added internal interfaces that act as a "spell check" for the developer when returning the parameters from the `getParameters` function
No real functionality changes. Deploy should still work as normal
**_Is this ready for review?:_** YES 

fix: Fix typing errors in ARM params and add interfaces

---

.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

Fix Issue and PR template to be repo specific. Remove copy-pasta from serverless framework

fix: Update GitHub Issue and PR templates

---

src/armTemplates/resources/apim.ts
src/services/resourceService.test.ts
src/services/resourceService.ts

- Updated parameter name in APIM arm template
- Fixed bug of sorting deployments in ascending order, when it should have been descending. This would have pretty serious consequences, because it means that the comparison of ARM templates would always be targeting the first ever deployment, not the most recent.
- Because the `sort()` function sorts the array in place, this bug was not being detected by the tests. Updated `resourceService` tests to create copies of the array rather than using the original reference when testing the validity of the result.
- Flipped the timestamp comparison operator
- Updated the string in `apim.ts`
- Deploy a service
- Make changes to an environment variable
- Deploy it again (should deploy ARM template)
- Change back to the original configuration
- Deploy …

fix: Sort deployments in descending order and fix APIM arm template

---

docs/DEPLOY.md
src/models/serverless.ts
src/services/resourceService.test.ts
src/services/resourceService.ts

Tagging for the Azure resource group as defined within the `provider`. Example
```yaml
...
provider:
tags:
TAG_1: tag1Value
TAG_2: tag2Value
```
- Check for existing resource group
- Merge tags from existing with tags from provider config
- Add tags to `createOrUpdate` call of resource group
- Deploy a service with `tags` defined in provider config
OR
- Manually define tag for resource group in Azure portal
- Deploy service
- Tag will not be lost

feat: Resource group tagging

---

README.md
src/plugins/offline/azureOfflinePlugin.ts
src/services/coreToolsService.ts
src/services/offlineService.test.ts
src/services/offlineService.ts

Allow users to pass additional arguments to spawned `func host start` process when running `sls offline`
Closes #365 
Created new option `spawnargs` (shortcut `a`) that takes a whitespace separated string containing additional arguments for new process.
*IMPORTANT* - PR is targeting linux & python support branch because of the significant changes to the way we use core tools within the plugin. That branch has a more forward facing approach to generalizing the use of `azure-functions-core-tools` and made more sense to branch off of it for this issue.
Run 
```
sls offline -a "--cors *"
```
Rather than `func host start` being spawned, `func host start --cors *` is spawned.
**Validate via `npm run lint`** …

feat: Allow additional arguments to spawned start process

---

src/armTemplates/resources/appServicePlan.test.ts
src/armTemplates/resources/appServicePlan.ts
src/models/armTemplates.ts
src/models/serverless.ts

Adds support to specify your scaling parameters for the app service plan hosting a premium functions app.
```yaml
provider:
name: azure
appServicePlan:
sku:
name: EP3 # Default is EP1
scale:
minWorkerCount: 3 # Default is 1
maxWorkerCount: 10 # Default is 10
```
Created new ARM template parameters that are auto configured via serverless yaml
Run unit tests with `npm run test`

feat: Support for specifying premium scaling options in serverless yaml

---

src/services/configService.test.ts
src/services/configService.ts
src/services/functionAppService.test.ts
src/services/rollbackService.test.ts
src/shared/constants.ts

Cache provider configuration in `serverless.variables` in `ConfigService` initialization
Closes #370 
- Check `serverless.variables` for cached config
- If it's not there, initialize the config and store it in `serverless.variables`
- See unit test.
- There is a log statement when provider config is initialized. This will not print if using cached config

perf: Cache provider config on initialization

---

.github/workflows/main.yml

Add a new GitHub workflow file to move newly opened issues to `To triage` column in Roadmap project

ci: Automatically move new issues to "To triage" column

---

src/plugins/remove/azureRemovePlugin.test.ts
src/plugins/remove/azureRemovePlugin.ts
src/services/resourceService.test.ts
src/services/resourceService.ts
src/shared/utils.ts

Requires user to enter resource group name as confirmation for group removal
Closes #380 
- Added utility function to wait for user input
- Check user input against configured resource group name
- Delete if results match
- Try to remove a non-deployed project
- Run `sls remove` and then just type `Enter` (empty string shouldn't match), removal won't happen
- Run `sls remove` and then type exact resource group name and removal will happen

feat: Prompt user for confirmation to remove resource group

---

src/services/packageService.test.ts
src/services/packageService.ts

Check to see if directory exists before trying to delete it
Closes #349 
Added one check to see if directory exists before reading/deleting it
- Create a new project
- Run `sls offline cleanup`
This would have failed before, as it would try to read and then delete directories named after your functions. This check prevents that from happening

fix: Don't try to clean up non-existent directories

---

README.md
src/plugins/azureBasePlugin.test.ts
src/plugins/azureBasePlugin.ts
src/plugins/func/azureFuncPlugin.test.ts
src/services/baseService.test.ts
src/services/baseService.ts
src/services/funcService.test.ts
src/services/loggingService.test.ts
src/services/loggingService.ts

A `LoggingService` class that allows for configurable verbosity of logging
- To line up with the SLS core, the flag `--verbose` or `-v` (shortcut) with no value sets to most verbose (debug)
- Users can also set a specific verbosity by providing a value after the flag. For example `-v error`, `-v debug`
Closes #374 
`LoggingService` is used by both the `BaseService` and the `BasePlugin`, which make all current logging calls. Added calls for `error`, `warn`, `info` and `debug` to both base service and base plugin. Did not update to use any of the new calls, everything is currently logged as `info`. Which means that if you were to set verbosity to either `warn` or `error` in the CLI, there would be no log statements shown
Add `-v error` to any CLI run. There will be no log statements …

feat: Logging Service to allow configurable verbosity

---

src/shared/bindings.json

Used correct displayName for cosmosDBTrigger to fix getting "Binding not supported" error.
Closes #389
Changed the displayName from $cosmosDBIn_displayName to $cosmosDBTriggerIn_displayName
Try to deploy the following function before & after the change:
```
cosmosChangeFeed:
handler: cosmosChangeFeed.handler
events:
- cosmosDB:
x-azure-settings:
direction: in
name: documents
databaseName: databaseName
collectionName: containerName
leaseCollectionName: leases
connectionStringSetting: COSMOS_DB_CONNECTION
createLeaseCollectionIfNotExists: true
```

Fix: Use correct displayName for cosmosDBTrigger

---

README.md
src/services/loggingService.test.ts
src/services/loggingService.ts

Currently, if you were to run `sls --version` or `sls -v`, the plugin causes it to fail because the `LoggingService` creates a shortcut for `--verbose`, which is `-v`. This conflicts with `--version`. This PR removes that shortcut and updates the documentation.
Only look for the full `verbose` flag within the options, set log level to `info` if undefined.
Run `sls --version`. It shouldn't fail.

fix: Remove -v shortcut for --verbose, conflicts with --version

---

jest.config.js
package-lock.json
package.json
src/services/offlineService.test.ts
src/shared/utils.ts

Instead of manually checking for the operating system, this uses the well known package `cross-spawn` (142M downloads per month) to spawn the process across operating systems.
Replaced the call to `child_process.spawn` with `cross-spawn.spawn`. Also added `jest-os-detection` that will only test the spawn calls the way that they should be expected on that native os rather than defining a property on the `process` object
Run `sls offline`. It will spawn on any operating system. Run `npm test` on mac, linux or windows. You'll see that 8 tests are skipped on any OS (each OS has 4 tests) …

feat: Use cross-spawn instead of adding .cmd

---

docs/CONFIG.md
docs/examples/apim.md
src/models/serverless.ts
src/plugins/func/azureFuncPlugin.test.ts
src/services/apimService.test.ts
src/services/apimService.ts
src/services/funcService.test.ts
src/services/funcService.ts
src/services/invokeService.ts
src/services/packageService.ts
src/shared/utils.test.ts
src/shared/utils.ts
src/test/mockFactory.ts

Users can now place the configuration in the event object rather than inside the nested `x-azure-settings` configuration. **Users can still use `x-azure-settings` if they want. This is NOT a breaking change**
Closes #371 and #12 
- Made `x-azure-settings` to be optional member of interface
- To maintain backwards compatibility, the binding utilities will first check to see if `x-azure-functions` is defined on the event object. If it is not, the event itself is used.
- The Func plugin and service that generate the .yml file were also updated to reflect the change
- Changes to the MockFactory, tests, and documentation were made to reflect the change
- Take any existing project, move the settings contained within `x-azure-settings` up one level and run `sls offline`. The bindings are …

feat: Eliminate need for 'x-azure-settings' config

---

README.md
src/index.ts
src/models/serverless.ts
src/plugins/apim/azureApimPlugin.ts
src/plugins/azureBasePlugin.ts
src/plugins/deploy/azureDeployPlugin.ts
src/plugins/info/azureInfoPlugin.test.ts
src/plugins/info/azureInfoPlugin.ts
src/plugins/invoke/azureInvokePlugin.ts
src/plugins/login/loginHooks.ts
src/plugins/remove/azureRemovePlugin.ts
src/plugins/rollback/azureRollbackPlugin.ts
src/services/baseService.ts
src/services/configService.ts
src/services/infoService.test.ts
src/services/infoService.ts
src/services/resourceService.ts
src/shared/constants.ts

An `info` command and a `--dryrun` option for deployment. This provides users a summary of the deployment that will or has happened without having to leave the CLI
Closes #7 
- Added an `info` plugin, with an accompanying service
- Added a `--dryrun` option to deploy plugin, which calls the `InfoService`
For a service that's already deployed:
```bash
sls info
```
To print the ARM template of most recent successful deployment:
```bash
sls info --arm
```
To get a summary of the service before deployment:
```bash
sls deploy --dryrun
```
To print the generated ARM template before deployment:
```bash
sls deploy --dryrun --arm
```
_Note: Some reported issues can be automatically …

feat: Info plugin and deploy dry run

---

src/armTemplates/resources/functionApp.test.ts
src/armTemplates/resources/functionApp.ts

Fixes issue of consumption linux function apps not being able to deploy
Re-added `reserved` property to ARM template
Deploy a linux azure function app

fix: Add functionAppReserved back into ARM template

---

src/services/functionAppService.test.ts
src/services/functionAppService.ts

In external deployment (always the case for .NET on linux), the deployed functions were not listed in the publishing process. This PR adds that fix.
- Abstracted out `logFunctions` method
- Added call to `logFunctions` after invoking `syncTriggers`
- Deploy a function app with `provider.deployment.external` set to true in `serverless.yml`
- You should see the functions listed after publishing

fix: Log functions in external deployment

---

scripts/condenseChangelog.js
scripts/version.sh

Generate the changelog on merges to dev or master. Generates condensed changelog if merges to master
- If a release type is prerelease, it will generate a full changelog, but if not prerelease, it will generate a condensed changelog
- Corrected switch of name and email for local git config
- Script for condensing changelog now accepts an argument for the new NPM version rather than depending on a tag to exist (tags are created and pushed after this point)
- Run `npm run changelog:condensed -- 2.0.0` (this will be the command executed when pipeline is run). The generated changelog should contain all changes in v2
_Note: Some reported issues can be automatically fixed by …

ci: Generate changelog in versioning script

---

.github/workflows/integration-tests-node.yml
integrationTests/configurations/dotnet22-linux/serverless.yml
integrationTests/configurations/dotnet31-linux/serverless.yml
src/plugins/package/azurePackagePlugin.test.ts
src/plugins/package/azurePackagePlugin.ts
src/services/configService.ts

Because the `syncTriggers` API that is used for "external" packages being published to a function app, this updates the .NET Core function apps to use the remote build option.
It also removes the "external" integration test calls in the GitHub workflow for Node function apps
- Checked for the OS in the package plugin before replacing the hook
- Remove call in config service to force .NET on linux to have `provider.external` to be true
- Remove `-external` from regex when invoking integration tests for node
Run the integration tests - .NET core on Linux should be much more stable, similar to python
_Note: Some reported issues can be automatically fixed by running `npm run …

fix: Update .NET to use remote build

---

src/plugins/package/azurePackagePlugin.test.ts
src/plugins/package/azurePackagePlugin.ts
src/services/configService.test.ts
src/services/configService.ts

Fixes the check for `windows` and `dotnet` before replacing packaging hook to instead compile the artifact. In the case where the `os` had not been defined (defaults to windows), the `ConfigService` had not yet initialized the default value. This moves the logic to the `ConfigService` when making the check to make sure it has been initialized
- Added a `shouldCompileBeforePublish` method in the `ConfigService` that indicates if hook should be replaced
- Replaced logic in plugin constructor to instead initialize a new `ConfigService` and make the call there instead
- Create a .NET serverless azure functions project
- Leave the `os` property undefined
- Run `sls package` - the process will spawn a command to `dotnet` to compile the service
_**Note: Run `npm run test:ci` to run all …

fix: Update package service to compile .NET for default OS

---

src/armTemplates/resources/functionApp.ts
src/config/runtime.test.ts
src/config/runtime.ts
src/services/offlineService.ts

Fix generated node runtime version for local.settings.json
Closes #467 
Re-used a function that was being used to set the worker runtime in app settings and added it to the `runtime.ts` file for broader use
1. `sls create -t azure-nodejs`
2. `sls offline`

fix: Fix runtime language in generated local settings

---

src/services/loggingService.test.ts
src/services/loggingService.ts

Fix log level setting to handle boolean case, previously expected empty string
Closes #470 
Updated the conditions to check for boolean in `--verbose` option, set to most verbose level
Run a command with `--verbose` on the end. Previously failed

fix: Fix log level setting to handle --verbose

---

integrationTests/tests/deploy.clvr.ts

Updated integration test to expect `int` instead of `tmp`

test: Fix integration test assertion

---

src/services/packageService.test.ts
src/services/packageService.ts

This commit fixes a bug when using the timer trigger where it tries to set the name of the binding. The name of the binding can't be set since there is no index found (-1)
Fixes: #444

fix: Check for valid index before setting name property

---

src/armTemplates/resources/functionApp.test.ts
src/armTemplates/resources/functionApp.ts
src/models/serverless.ts
src/plugins/package/azurePackagePlugin.ts

Enable custom app insights instrumentation key 
```yaml
provider:
appInsights:
instrumentationKey: {your_key}
```
If an instrumentation key is added, arm template will use that value instead of the key from the generated template
**Out of scope**: The default template will still create an instance of app insights - should be future PR to remove that
Deploy a function app with a custom app insights instrumentation key

feat: Allow custom app insights instrumentation key

---

.github/workflows/integration.yml
.github/workflows/publish.yml

When I merged the master branch this started failing in my repo, so adding this to only run the tag on the main repo, not on forks

fix: Updated publishing script and only run tag on the main repo, not forks

---

package-lock.json
package.json

The `semver` package is no longer being used, so it doesn't need to be listed as a dependency.
I removed it from `dependencies` in `package.json`
```
❯ rg --files-with-matches 'semver'
integrationTests/configurations/node16-linux-webpack/package-lock.json
integrationTests/configurations/node12-linux/package-lock.json
integrationTests/configurations/node18-linux-webpack/package-lock.json
integrationTests/configurations/node14-windows/package-lock.json
integrationTests/configurations/node16-linux/package-lock.json
integrationTests/configurations/node12-linux-webpack/package-lock.json
integrationTests/configurations/node16-windows-webpack/package-lock.json
integrationTests/configurations/node14-windows-webpack/package-lock.json
integrationTests/configurations/node18-windows-webpack/package-lo …
```

fix: remove unused `semver` dependency

---

package-lock.json
package.json
src/services/apimService.test.ts

Removed `lodash` as a required dependency for this plugin.
I replaced the single usage of `lodash` with a native equivalent, and then I removed it from `dependencies` in `package.json`
```
❯ rg --files-with-matches 'lodash'
integrationTests/configurations/node16-linux-webpack/package-lock.json
integrationTests/configurations/node12-linux/package-lock.json
integrationTests/configurations/node18-linux-webpack/package-lock.json
integrationTests/configurations/node14-windows/package-lock.json
integrationTests/configurations/node16-linux/package-lock.json
integrationTests/configurations/node12-linux-webpack/package-lock.json
integrationTests/configurations/node18-windows-webpack/package-lock.json
integrationTests/configurations/node16-windows-webpack/package-lock.json …
```

refactor: remove `lodash`
